# Generated by Django 6.0.7 on 2026-09-03 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('action', models.CharField(choices=[('profile_update', 'Profile Update'), ('resume_upload', 'Resume Upload'), ('internship_save', 'Internship Saved'), ('internship_apply', 'Internship Applied'), ('recommendation_view', 'Recommendation Viewed'), ('account_activated', 'Account Activated'), ('account_deactivated', 'Account Deactivated')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Activity Log',
                'verbose_name_plural': 'Student Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
