# Generated by Django 6.0.7 on 2026-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_timestampedmodel_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-recommendation_date'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_student_b5e79f_idx',
            old_name='recommendations_student_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_interns_85ded0_idx',
            old_name='recommendations_internship_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_overall_64444b_idx',
            old_name='recommendations_overall_score_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_recomme_b411a0_idx',
            old_name='recommendations_date_idx',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
    ]
