# Generated by Django 6.0.7 on 2026-08-28 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_internship_company_internship_content_hash_and_more'),
        ('recommendations', '0003_alter_recommendation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Match explanation dictionary or text (reasons, matched skills, highlights).'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='work_mode_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Work mode relevance score (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'internship')},
        ),
    ]
