# Generated by Django 6.0.7 on 2026-08-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True)),
                ('internship_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', max_length=20)),
                ('work_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('either', 'Either')], default='either', max_length=20)),
                ('compensation_preference', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('either', 'Either')], default='either', max_length=20)),
                ('minimum_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compensation_currency', models.CharField(default='USD', max_length=10)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('internship_duration_min_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('internship_duration_max_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='student_cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
