# Generated by Django 6.0.7 on 2026-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0006_alter_studentcv_extracted_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
