# Generated by Django 6.0.7 on 2026-08-25 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0010_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='student_cvs/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
    ]
