"""Seed the Task 1.3 Skill and CareerInterest catalogues.

Usage::

    python manage.py seed_skill_catalogue        # create missing, keep existing
    python manage.py seed_skill_catalogue --reset # recreate all (destructive)

The catalogues live in the database (there are no fixture files), so without
this command the Skills & Interests section has an empty list to choose from.
This command is idempotent: it only creates rows that do not already exist, so
it is safe to run on every deploy.
"""

from django.core.management.base import BaseCommand

from apps.internships.models import Skill
from apps.students.models import CareerInterest

# category -> (skill name, short description)
SKILLS = {
    "Programming Languages": [
        ("Python", "General-purpose scripting and backend language."),
        ("JavaScript", "Core language of the modern web."),
        ("TypeScript", "Typed superset of JavaScript."),
        ("Java", "Object-oriented language used in enterprise and Android."),
        ("C", "Foundational systems programming language."),
        ("C++", "Systems language used in games, HPC, and embedded."),
        ("C#", "Language for .NET, Unity, and enterprise apps."),
        ("Go", "Fast, concurrent language for backend and cloud services."),
        ("Rust", "Memory-safe systems language."),
        ("Kotlin", "Modern JVM language, first-class for Android."),
        ("Swift", "Apple ecosystem language for iOS and macOS."),
        ("PHP", "Server-side language widely used on the web."),
        ("Ruby", "Dynamic language popular for web apps via Rails."),
        ("R", "Statistical computing and data analysis."),
        ("MATLAB", "Numerical computing and engineering analysis."),
        ("SQL", "Query language for relational databases."),
        ("HTML", "Markup language for web structure."),
        ("CSS", "Style sheet language for web presentation."),
        ("Bash", "UNIX/Linux shell scripting."),
        ("PowerShell", "Windows and cross-platform scripting."),
        ("Scala", "Scalable JVM language combining OOP and functional styles."),
        ("Dart", "Language used with the Flutter UI toolkit."),
        ("Elixir", "Functional language built on the Erlang VM."),
        ("Solidity", "Smart-contract language for Ethereum."),
    ],
    "Web & Frameworks": [
        ("React", "JavaScript library for building user interfaces."),
        ("React Native", "Cross-platform mobile framework using React."),
        ("Angular", "TypeScript-based web application framework."),
        ("Vue.js", "Progressive JavaScript framework for UIs."),
        ("Next.js", "React framework for server-rendered web apps."),
        ("Node.js", "JavaScript runtime for server-side applications."),
        ("Express.js", "Minimalist Node.js web framework."),
        ("Django", "High-level Python web framework."),
        ("Flask", "Lightweight Python web framework."),
        ("FastAPI", "Modern async Python web framework with OpenAPI."),
        ("Spring Boot", "Java framework for production web services."),
        ("ASP.NET Core", "Cross-platform .NET web framework."),
        ("Ruby on Rails", "Full-stack framework for productive web apps."),
        ("Svelte", "Compiler-driven UI framework."),
        ("Tailwind CSS", "Utility-first CSS framework."),
        ("Bootstrap", "Popular CSS component framework."),
        ("jQuery", "Legacy JavaScript library for DOM manipulation."),
        ("Laravel", "PHP web application framework."),
        ("GraphQL", "Query language for APIs."),
        ("REST API", "Architectural style for HTTP web services."),
        ("WebSocket", "Protocol for full-duplex realtime communication."),
        ("Flutter", "Cross-platform UI toolkit from Google."),
        ("Redux", "State-management library for JavaScript apps."),
    ],
    "Data & Databases": [
        ("PostgreSQL", "Open-source relational database."),
        ("MySQL", "Popular open-source relational database."),
        ("MongoDB", "Document-oriented NoSQL database."),
        ("SQLite", "Embedded relational database."),
        ("Redis", "In-memory data store used for caching."),
        ("Elasticsearch", "Distributed search and analytics engine."),
        ("Apache Kafka", "Distributed event-streaming platform."),
        ("Apache Spark", "Unified analytics engine for large-scale data."),
        ("Pandas", "Python library for data manipulation."),
        ("NumPy", "Python library for numerical computing."),
        ("Data Analysis", "Inspecting and modeling data to derive insights."),
        ("ETL", "Extract, transform, load data pipelines."),
        ("Data Modeling", "Designing database schemas and relationships."),
        ("Database Design", "Structuring data storage for performance and integrity."),
        ("BigQuery", "Google serverless data warehouse."),
    ],
    "Machine Learning & AI": [
        ("Machine Learning", "Building models that learn from data."),
        ("Deep Learning", "Neural networks with multiple hidden layers."),
        ("Natural Language Processing", "Processing and understanding human language."),
        ("Computer Vision", "Enabling machines to interpret visual data."),
        ("TensorFlow", "Google open-source ML framework."),
        ("PyTorch", "Meta open-source deep-learning framework."),
        ("scikit-learn", "Python library for classical machine learning."),
        ("Keras", "High-level deep-learning API."),
        ("Large Language Models", "Working with and fine-tuning LLMs."),
        ("Prompt Engineering", "Designing effective prompts for LLMs."),
        ("LangChain", "Framework for building LLM applications."),
        ("Generative AI", "Building models that generate new content."),
        ("Recommendation Systems", "Building systems that suggest relevant items."),
        ("Neural Networks", "Computing systems inspired by the brain."),
        ("Data Visualization", "Representing data in visual form."),
        ("Statistical Analysis", "Applying statistics to derive conclusions."),
        ("Transformers", "Attention-based model architecture for AI."),
        ("AI Ethics", "Responsible and fair development of AI."),
    ],
    "Cloud & DevOps": [
        ("AWS", "Amazon cloud computing platform."),
        ("Microsoft Azure", "Microsoft cloud computing platform."),
        ("Google Cloud", "Google cloud computing platform."),
        ("Docker", "Containerization platform."),
        ("Kubernetes", "Container orchestration platform."),
        ("CI/CD", "Continuous integration and delivery pipelines."),
        ("Jenkins", "Automation server for CI/CD."),
        ("Git", "Distributed version control system."),
        ("GitHub", "Web-based hosting and collaboration for Git."),
        ("GitLab", "DevOps platform around Git."),
        ("Linux", "Open-source operating system."),
        ("Nginx", "Web server and reverse proxy."),
        ("Terraform", "Infrastructure-as-code tool."),
        ("Ansible", "Configuration-management and automation tool."),
        ("Linux Administration", "Managing and configuring Linux servers."),
        ("Networking", "Fundamentals of computer networks."),
        ("Shell Scripting", "Writing automation scripts for the shell."),
    ],
    "Mobile & Desktop": [
        ("Android Development", "Building apps for the Android platform."),
        ("iOS Development", "Building apps for iOS and Apple platforms."),
        ("Mobile App Development", "Designing and building mobile applications."),
        ("User Interface Design", "Designing intuitive and usable interfaces."),
        ("Cross-platform Development", "Building apps that run on multiple platforms."),
    ],
    "Cybersecurity & Networking": [
        ("Cybersecurity", "Protecting systems and data from threats."),
        ("Network Security", "Securing network infrastructure."),
        ("Penetration Testing", "Authorized simulated cyber attacks."),
        ("Cryptography", "Securing communication through encoding."),
        ("Ethical Hacking", "Finding vulnerabilities responsibly."),
        ("Firewalls", "Securing network boundaries."),
        ("Vulnerability Assessment", "Identifying security weaknesses."),
    ],
    "Soft Skills": [
        ("Communication", "Effectively conveying ideas in writing and speech."),
        ("Teamwork", "Collaborating effectively with others."),
        ("Problem Solving", "Analyzing issues and crafting solutions."),
        ("Leadership", "Guiding and motivating a team."),
        ("Time Management", "Prioritizing tasks to meet deadlines."),
        ("Adaptability", "Adjusting effectively to changing conditions."),
        ("Critical Thinking", "Reasoning and evaluating information objectively."),
        ("Public Speaking", "Presenting ideas to an audience."),
        ("Written Communication", "Producing clear, effective written material."),
    ],
    "Graphics & Design": [
        ("Adobe Photoshop", "Image editing and manipulation software."),
        ("Adobe Illustrator", "Vector graphics editor for illustrations."),
        ("Adobe InDesign", "Layout and page design software."),
        ("Figma", "Collaborative interface design tool."),
        ("Sketch", "Digital design platform for UI/UX."),
        ("Canva", "Online design tool for graphics and media."),
        ("CorelDRAW", "Vector illustration software."),
        ("Affinity Designer", "Professional graphic design software."),
        ("GIMP", "Open-source image editing software."),
        ("Inkscape", "Open-source vector graphics editor."),
        ("Blender", "3D creation suite for modeling and animation."),
        ("Cinema 4D", "3D motion graphics software."),
        ("After Effects", "Motion graphics and visual effects."),
        ("Premiere Pro", "Video editing software."),
        ("Final Cut Pro", "Professional video editing software."),
        ("DaVinci Resolve", "Professional video editing and color grading."),
        ("Lightroom", "Photo editing and management software."),
        ("Graphic Design", "Creating visual content for communication."),
        ("UI Design", "Designing user interfaces for digital products."),
        ("UX Design", "Designing user experiences and interactions."),
        ("Typography", "Art of arranging type for readability and appeal."),
        ("Color Theory", "Understanding color relationships and harmony."),
        ("Brand Identity", "Creating consistent visual brand elements."),
        ("Logo Design", "Creating distinctive brand logos."),
        ("Print Design", "Designing for physical media and publications."),
        ("Digital Art", "Creating artwork using digital tools."),
        ("3D Modeling", "Creating three-dimensional digital models."),
        ("Animation", "Creating moving images and visual effects."),
        ("Video Editing", "Manipulating and arranging video footage."),
        ("Motion Graphics", "Animated graphic design elements."),
    ],
    "Video & Multimedia": [
        ("Video Production", "Planning and filming video content."),
        ("Video Editing", "Post-production editing of video footage."),
        ("Motion Graphics", "Animated graphic elements in video."),
        ("Visual Effects", "Creating computer-generated visual effects."),
        ("Sound Design", "Creating and editing audio for media."),
        ("Audio Editing", "Manipulating and enhancing audio recordings."),
        ("Color Grading", "Adjusting color and tone in video."),
        ("Storyboarding", "Planning visual sequences for video."),
        ("Screenwriting", "Writing scripts for video and film."),
        ("Cinematography", "Art of filming and camera work."),
        ("Lighting Design", "Setting up lighting for video production."),
        ("Camera Operation", "Operating video cameras and equipment."),
        ("Live Streaming", "Broadcasting video content in real-time."),
        ("Podcasting", "Creating and producing audio content."),
        ("Voice Over", "Recording narration and voice acting."),
        ("Multimedia Design", "Creating integrated media experiences."),
        ("Interactive Media", "Designing engaging interactive content."),
    ],
    "Frontend Development": [
        ("React", "JavaScript library for building user interfaces."),
        ("React Native", "Cross-platform mobile framework using React."),
        ("Vue.js", "Progressive JavaScript framework for UIs."),
        ("Angular", "TypeScript-based web application framework."),
        ("Svelte", "Compiler-driven UI framework."),
        ("Next.js", "React framework for server-rendered web apps."),
        ("Nuxt.js", "Vue.js framework for server-side rendering."),
        ("TypeScript", "Typed superset of JavaScript."),
        ("JavaScript", "Core language of the modern web."),
        ("HTML", "Markup language for web structure."),
        ("CSS", "Style sheet language for web presentation."),
        ("Tailwind CSS", "Utility-first CSS framework."),
        ("Bootstrap", "Popular CSS component framework."),
        ("Sass", "CSS preprocessor for styling."),
        ("Less", "CSS preprocessor extending CSS."),
        ("Webpack", "Module bundler for JavaScript."),
        ("Vite", "Build tool for modern web development."),
        ("jQuery", "Legacy JavaScript library for DOM manipulation."),
        ("Redux", "State-management library for JavaScript apps."),
        ("MobX", "State management library for JavaScript."),
        ("GraphQL", "Query language for APIs."),
        ("REST API", "Architectural style for HTTP web services."),
        ("Responsive Design", "Designing for multiple screen sizes."),
        ("Progressive Web Apps", "Web apps with native-like features."),
        ("Web Accessibility", "Making web content accessible to all."),
        ("Cross-Browser Compatibility", "Ensuring consistent behavior across browsers."),
        ("Performance Optimization", "Improving web application speed."),
        ("Testing", "Writing tests for frontend code."),
        ("Jest", "JavaScript testing framework."),
        ("Cypress", "End-to-end testing framework."),
    ],
    "Backend Development": [
        ("Node.js", "JavaScript runtime for server-side applications."),
        ("Express.js", "Minimalist Node.js web framework."),
        ("Django", "High-level Python web framework."),
        ("Flask", "Lightweight Python web framework."),
        ("FastAPI", "Modern async Python web framework with OpenAPI."),
        ("Spring Boot", "Java framework for production web services."),
        ("ASP.NET Core", "Cross-platform .NET web framework."),
        ("Ruby on Rails", "Full-stack framework for productive web apps."),
        ("Laravel", "PHP web application framework."),
        ("PHP", "Server-side language widely used on the web."),
        ("Go", "Fast, concurrent language for backend and cloud services."),
        ("Rust", "Memory-safe systems language."),
        ("Java", "Object-oriented language used in enterprise and Android."),
        ("Python", "General-purpose scripting and backend language."),
        ("C#", "Language for .NET, Unity, and enterprise apps."),
        ("Kotlin", "Modern JVM language, first-class for Android."),
        ("Scala", "Scalable JVM language combining OOP and functional styles."),
        ("Elixir", "Functional language built on the Erlang VM."),
        ("PostgreSQL", "Open-source relational database."),
        ("MySQL", "Popular open-source relational database."),
        ("MongoDB", "Document-oriented NoSQL database."),
        ("Redis", "In-memory data store used for caching."),
        ("SQLite", "Embedded relational database."),
        ("GraphQL", "Query language for APIs."),
        ("REST API", "Architectural style for HTTP web services."),
        ("WebSocket", "Protocol for full-duplex realtime communication."),
        ("Microservices", "Architectural style for distributed systems."),
        ("API Design", "Designing effective API interfaces."),
        ("Authentication", "Implementing user authentication systems."),
        ("Authorization", "Managing access control and permissions."),
        ("OAuth", "Open standard for access delegation."),
        ("JWT", "JSON Web Tokens for authentication."),
        ("Serverless", "Cloud-native application architecture."),
        ("Docker", "Containerization platform."),
        ("Kubernetes", "Container orchestration platform."),
    ],
    "App Development": [
        ("Flutter", "Cross-platform UI toolkit from Google."),
        ("React Native", "Cross-platform mobile framework using React."),
        ("Android Development", "Building apps for the Android platform."),
        ("iOS Development", "Building apps for iOS and Apple platforms."),
        ("Swift", "Apple ecosystem language for iOS and macOS."),
        ("Kotlin", "Modern JVM language, first-class for Android."),
        ("Dart", "Language used with the Flutter UI toolkit."),
        ("Mobile App Development", "Designing and building mobile applications."),
        ("Cross-platform Development", "Building apps that run on multiple platforms."),
        ("Native Development", "Building platform-specific applications."),
        ("Hybrid Development", "Building apps with web technologies."),
        ("Xamarin", "Cross-platform app development framework."),
        ("Ionic", "Framework for hybrid mobile apps."),
        ("Unity", "Game engine for mobile and desktop apps."),
        ("Mobile UI Design", "Designing interfaces for mobile devices."),
        ("App Store Optimization", "Optimizing apps for app store visibility."),
        ("Push Notifications", "Implementing notification systems."),
        ("Mobile Testing", "Testing mobile applications."),
        ("App Performance", "Optimizing mobile app performance."),
    ],
    "Web Development": [
        ("React", "JavaScript library for building user interfaces."),
        ("Vue.js", "Progressive JavaScript framework for UIs."),
        ("Angular", "TypeScript-based web application framework."),
        ("Next.js", "React framework for server-rendered web apps."),
        ("Nuxt.js", "Vue.js framework for server-side rendering."),
        ("Svelte", "Compiler-driven UI framework."),
        ("JavaScript", "Core language of the modern web."),
        ("TypeScript", "Typed superset of JavaScript."),
        ("HTML", "Markup language for web structure."),
        ("CSS", "Style sheet language for web presentation."),
        ("Tailwind CSS", "Utility-first CSS framework."),
        ("Bootstrap", "Popular CSS component framework."),
        ("Sass", "CSS preprocessor for styling."),
        ("Node.js", "JavaScript runtime for server-side applications."),
        ("Express.js", "Minimalist Node.js web framework."),
        ("Django", "High-level Python web framework."),
        ("Flask", "Lightweight Python web framework."),
        ("FastAPI", "Modern async Python web framework with OpenAPI."),
        ("Ruby on Rails", "Full-stack framework for productive web apps."),
        ("Laravel", "PHP web application framework."),
        ("PHP", "Server-side language widely used on the web."),
        ("GraphQL", "Query language for APIs."),
        ("REST API", "Architectural style for HTTP web services."),
        ("WebSocket", "Protocol for full-duplex realtime communication."),
        ("Responsive Design", "Designing for multiple screen sizes."),
        ("Progressive Web Apps", "Web apps with native-like features."),
        ("Web Accessibility", "Making web content accessible to all."),
        ("SEO", "Search engine optimization for websites."),
        ("Web Performance", "Optimizing website speed and performance."),
        ("Cross-Browser Compatibility", "Ensuring consistent behavior across browsers."),
        ("Content Management Systems", "Managing website content with CMS."),
        ("WordPress", "Popular content management system."),
        ("Drupal", "Enterprise content management platform."),
    ],
}

# career interest -> short description
CAREER_INTERESTS = {
    "Software Development": "Building and maintaining software applications.",
    "Web Development": "Designing and building websites and web apps.",
    "Mobile Development": "Building applications for mobile devices.",
    "Data Science": "Extracting insights and value from data.",
    "Data Analysis": "Analyzing data to inform decisions.",
    "Machine Learning": "Building systems that learn from data.",
    "Artificial Intelligence": "Developing intelligent systems and algorithms.",
    "DevOps": "Automating and improving software delivery and operations.",
    "Cloud Computing": "Designing and managing cloud infrastructure.",
    "Cybersecurity": "Protecting systems, networks, and data.",
    "Information Security": "Safeguarding information assets.",
    "UI/UX Design": "Designing user interfaces and experiences.",
    "Product Management": "Defining and shipping valuable products.",
    "Project Management": "Planning and executing projects on time.",
    "Quality Assurance": "Ensuring software quality through testing.",
    "Database Administration": "Managing and maintaining databases.",
    "Network Engineering": "Designing and managing computer networks.",
    "System Administration": "Administering servers and IT infrastructure.",
    "Game Development": "Designing and building video games.",
    "Robotics": "Designing and building robots and automation.",
    "Embedded Systems": "Developing software for hardware devices.",
    "Blockchain": "Developing decentralized applications.",
    "Research": "Conducting scientific and technical research.",
    "Teaching": "Educating and mentoring others.",
    "Technical Writing": "Documenting technical concepts clearly.",
    "Business Intelligence": "Transforming data into actionable insight.",
    "Data Engineering": "Building data pipelines and infrastructure.",
    "Full Stack Development": "Working across frontend and backend.",
    "Frontend Development": "Building client-side user interfaces.",
    "Backend Development": "Building server-side logic and APIs.",
    "Automation Testing": "Automating software test workflows.",
    "Site Reliability Engineering": "Keeping systems reliable and scalable.",
    "Agile Methodologies": "Working in agile, iterative delivery.",
}

CATEGORY_DEFAULT = "Other"
DESCRIPTION_DEFAULT = ""


class Command(BaseCommand):
    help = "Seed the Task 1.3 Skill and CareerInterest catalogues."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete all existing skills/interests before seeding (destructive).",
        )

    def handle(self, *args, **options):
        if options["reset"]:
            Skill.objects.all().delete()
            CareerInterest.objects.all().delete()
            self.stdout.write(self.style.WARNING("Cleared existing Skill/CareerInterest rows."))

        created_skills = 0
        created_interests = 0

        for category, items in SKILLS.items():
            for name, description in items:
                _, created = Skill.objects.get_or_create(
                    name=name,
                    defaults={
                        "category": category,
                        "description": description,
                        "is_active": True,
                    },
                )
                created_skills += int(created)

        for name, description in CAREER_INTERESTS.items():
            _, created = CareerInterest.objects.get_or_create(
                name=name,
                defaults={
                    "description": description,
                    "is_active": True,
                },
            )
            created_interests += int(created)

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Skills present: {Skill.objects.filter(is_active=True).count()} "
                f"({created_skills} created), Career interests present: "
                f"{CareerInterest.objects.filter(is_active=True).count()} ({created_interests} created)."
            )
        )
