# Generated by Django 6.0.7 on 2026-08-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('website', 'Website'), ('organization', 'Organization'), ('other', 'Other')], max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organization_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('internship_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], max_length=20)),
                ('work_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], max_length=20)),
                ('compensation_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('minimum_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compensation_currency', models.CharField(blank=True, max_length=10)),
                ('compensation_period', models.CharField(blank=True, help_text='Example: monthly, hourly, total', max_length=30)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('duration_min_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_max_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('application_url', models.URLField()),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='internships.internshipsource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='internships_status_f7773d_idx'), models.Index(fields=['country', 'city'], name='internships_country_5730c2_idx'), models.Index(fields=['internship_type'], name='internships_interns_88e740_idx'), models.Index(fields=['compensation_type'], name='internships_compens_0ef3f3_idx'), models.Index(fields=['application_deadline'], name='internships_applica_3dd7e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_internship_source_external_id')],
            },
        ),
    ]
