# Generated by Django 6.0.7 on 2026-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_skill_remove_internship_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
