# Generated by Django 6.0.7 on 2026-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_internship_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
