# Generated by Django 6.0.7 on 2026-08-24 19:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_alter_internship_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
