# Generated by Django 6.0.7 on 2026-08-24 19:27

import pgvector.django.vector
from django.db import migrations


def apply_migration(apps, schema_editor):
    """Apply vector dimension change only on PostgreSQL."""
    if schema_editor.connection.vendor != "postgresql":
        return  # Skip on SQLite

    with schema_editor.connection.cursor() as cursor:
        # Check if embedding column exists and its current type
        cursor.execute("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'internships_internship'
            AND column_name = 'embedding';
        """)
        result = cursor.fetchone()
        
        if not result:
            # Column doesn't exist, create it as vector(384)
            cursor.execute(
                "ALTER TABLE internships_internship ADD COLUMN embedding vector(384);"
            )
        elif result[1] == 'USER-DEFINED':
            # Column is already a vector type, drop and recreate with correct dimension
            cursor.execute(
                "ALTER TABLE internships_internship DROP COLUMN IF EXISTS embedding;"
            )
            cursor.execute(
                "ALTER TABLE internships_internship ADD COLUMN embedding vector(384);"
            )
        # If it's JSONB, leave it as is (for test databases)


def reverse_migration(apps, schema_editor):
    """Reverse migration - drop embedding column."""
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE internships_internship DROP COLUMN IF EXISTS embedding;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_alter_internship_embedding'),
    ]

    operations = [
        migrations.RunPython(apply_migration, reverse_migration),
    ]
