# Generated by Django 6.0.7 on 2026-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_alter_internship_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='embedding_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='embedding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
