# Generated by Django 6.0.7 on 2026-08-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0011_internship_embedding_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Final weighted score (0-100)', max_digits=5)),
                ('skill_score', models.DecimalField(blank=True, decimal_places=2, help_text='Skill matching score (0-100)', max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, help_text='Education relevance score (0-100)', max_digits=5, null=True)),
                ('interest_score', models.DecimalField(blank=True, decimal_places=2, help_text='Interest/career preference score (0-100)', max_digits=5, null=True)),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, help_text='Experience relevance score (0-100)', max_digits=5, null=True)),
                ('location_score', models.DecimalField(blank=True, decimal_places=2, help_text='Location match score (0-100)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='recommended', max_length=20)),
                ('recommendation_date', models.DateTimeField(auto_now_add=True, help_text='When this recommendation was generated')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the student viewed this recommendation', null=True)),
                ('saved_at', models.DateTimeField(blank=True, help_text='When the student saved this internship', null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the student applied to this internship', null=True)),
                ('ignored_at', models.DateTimeField(blank=True, help_text='When the student ignored this recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommendation_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='internships_student_86ed13_idx'), models.Index(fields=['internship', 'status'], name='internships_interns_3aa9db_idx'), models.Index(fields=['overall_score'], name='internships_overall_c045b9_idx'), models.Index(fields=['recommendation_date'], name='internships_recomme_8b3d01_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'internship'), name='unique_student_internship_recommendation')],
            },
        ),
    ]
