# Generated by Django 6.0.7 on 2026-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='preference_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preference match score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='salary_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salary match score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='semantic_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semantic embedding score (0-100)', max_digits=5, null=True),
        ),
    ]
