# Generated by Django 6.0.7 on 2026-08-28 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_timestampedmodel_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='internshipsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='internship',
                    index=models.Index(fields=['status'], name='internships_status_f7773d_idx'),
                ),
                migrations.AddIndex(
                    model_name='internship',
                    index=models.Index(fields=['country', 'city'], name='internships_country_5730c2_idx'),
                ),
                migrations.AddIndex(
                    model_name='internship',
                    index=models.Index(fields=['internship_type'], name='internships_interns_88e740_idx'),
                ),
                migrations.AddIndex(
                    model_name='internship',
                    index=models.Index(fields=['compensation_type'], name='internships_compens_0ef3f3_idx'),
                ),
                migrations.AddIndex(
                    model_name='internship',
                    index=models.Index(fields=['application_deadline'], name='internships_applica_3dd7e1_idx'),
                ),
            ],
        ),
    ]
