# Generated by Django 6.0.7 on 2026-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0016_alter_internship_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Skill category (e.g. Programming Languages, Frameworks, Cloud, Soft Skills).', max_length=100),
        ),
    ]
