# Generated by Django 6.0.7 on 2026-08-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('data_sources', '0002_rename_website_url_datasource_base_url_and_more'),
        ('internships', '0017_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company publishing this internship (Section 3.6).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='companies.company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of title+company+description for duplicate detection (Task 5.x).', max_length=64),
        ),
        migrations.AddField(
            model_name='internship',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Origin data source, null for company-direct postings (Section 3.6).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='data_sources.datasource'),
        ),
        migrations.AddField(
            model_name='internship',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Application closing deadline.', null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='posted_date',
            field=models.DateTimeField(blank=True, help_text='Date when internship was posted by employer/source.', null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_education',
            field=models.CharField(blank=True, help_text='Required education level (e.g. Bachelor, Master, PhD).', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='required_experience',
            field=models.CharField(blank=True, help_text='Required experience level (e.g. Beginner, Intermediate, None).', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stipend / salary amount if specified.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='internships.internshipsource'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('removed', 'Removed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InternshipSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.skill')),
            ],
            options={
                'verbose_name': 'Internship Skill',
                'verbose_name_plural': 'Internship Skills',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('internship', 'skill'), name='unique_internship_skill')],
                'unique_together': {('internship', 'skill')},
            },
        ),
    ]
