# Generated by Django 6.0.7 on 2026-08-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_internship_company_internship_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time this listing was seen by a collection run (Task 5.7).', null=True),
        ),
        migrations.CreateModel(
            name='InternshipDuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('organization_name', models.CharField(max_length=300)),
                ('application_url', models.URLField()),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('similarity_score', models.FloatField(blank=True, help_text='rapidfuzz token ratio (0-100) between the two titles.', null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this candidate listing was seen by the collector (Task 5.7).', null=True)),
                ('internship', models.ForeignKey(help_text='Stored internship this candidate was matched against.', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='internships.internship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
