# Generated by Django 6.0.7 on 2026-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_internship_last_seen_at_internshipduplicateflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged for admin review (broken links, low-confidence skills, etc.) instead of auto-published (Section 3.10.8, Task 5.9).'),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills_review',
            field=models.JSONField(blank=True, default=list, help_text='Low-confidence skill matches flagged for the Task 5.9 admin review.'),
        ),
        migrations.AddField(
            model_name='internship',
            name='url_validation',
            field=models.JSONField(blank=True, default=dict, help_text='Per-URL validation results (HEAD/GET status, error) from Task 5.9.'),
        ),
        migrations.AddField(
            model_name='internship',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When the listing URLs were last validated by the Task 5.9 collector task.', null=True),
        ),
    ]
