# Generated by Django 6.0.7 on 2026-08-28 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0016_alter_internship_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('apply_clicked', models.BooleanField(default=True, help_text='True when the student was redirected to the employer apply URL.')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_histories', to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application history',
                'verbose_name_plural': 'Application history',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'internship'), name='unique_student_internship_application_history')],
            },
        ),
    ]
