# Generated by Django 6.0.7 on 2026-08-28 20:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('internships', '0018_internship_company_internship_content_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationhistory',
            old_name='apply_clicked',
            new_name='clicked_apply',
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='applied_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the student clicked apply.'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationhistory',
            unique_together={('student', 'internship')},
        ),
    ]
