# Generated by Django 6.0.7 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_skill_remove_internship_required_skills_and_more'),
        ('student_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='internships.skill'),
        ),
    ]
