# Generated by Django 6.0.7 on 2026-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0002_remove_studentprofile_skills_studentprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
