# Generated by Django 6.0.7 on 2026-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0004_studentcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcv',
            name='extracted_certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentcv',
            name='extracted_education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentcv',
            name='extracted_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentcv',
            name='extracted_projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentcv',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
