# Generated by Django 6.0.7 on 2026-08-24 15:19

from django.db import migrations, models


def convert_text_to_json(apps, schema_editor):
    """Convert existing text fields to empty JSON arrays before field type change."""
    StudentCV = apps.get_model('student_profiles', 'StudentCV')
    
    for cv in StudentCV.objects.all():
        # Convert text fields to empty lists if they're not valid JSON
        if cv.extracted_education and not isinstance(cv.extracted_education, list):
            cv.extracted_education = []
        if cv.extracted_experience and not isinstance(cv.extracted_experience, list):
            cv.extracted_experience = []
        if cv.extracted_projects and not isinstance(cv.extracted_projects, list):
            cv.extracted_projects = []
        if cv.extracted_certifications and not isinstance(cv.extracted_certifications, list):
            cv.extracted_certifications = []
        
        # Ensure all fields are lists
        cv.extracted_education = cv.extracted_education or []
        cv.extracted_experience = cv.extracted_experience or []
        cv.extracted_projects = cv.extracted_projects or []
        cv.extracted_certifications = cv.extracted_certifications or []
        
        cv.save(update_fields=['extracted_education', 'extracted_experience', 
                              'extracted_projects', 'extracted_certifications'])


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0005_studentcv_extracted_certifications_and_more'),
    ]

    operations = [
        # First convert existing data to valid JSON format
        migrations.RunPython(convert_text_to_json, migrations.RunPython.noop),
        # Then change field types
        migrations.AlterField(
            model_name='studentcv',
            name='extracted_certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='extracted_education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='extracted_experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='extracted_projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
