# Generated by Django 6.0.7 on 2026-08-28 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0012_timestampedmodel_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Other')], max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('current_year', models.CharField(blank=True, help_text='Current academic year or status (e.g. 1st Year, 2nd Year, 3rd Year, Final Year).', max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('preferred_country', models.CharField(blank=True, max_length=100)),
                ('preferred_city', models.CharField(blank=True, max_length=100)),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', max_length=20)),
                ('internship_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('either', 'Either')], default='either', max_length=20)),
                ('availability_start', models.DateField(blank=True, null=True)),
                ('availability_end', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('user', models.OneToOneField(help_text='User account associated with this student profile (composition: deleting User deletes Student).', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
