# Generated by Django 6.0.7 on 2026-08-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_skill_category'),
        ('student_profiles', '0013_alter_cv_updated_at_alter_studentcv_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career Interest',
                'verbose_name_plural': 'Career Interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='student_profiles.careerinterest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='student_profiles.student')),
            ],
            options={
                'verbose_name': 'Student Interest',
                'verbose_name_plural': 'Student Interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='students', through='student_profiles.StudentInterest', to='student_profiles.careerinterest'),
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='internships.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='student_profiles.student')),
            ],
            options={
                'verbose_name': 'Student Skill',
                'verbose_name_plural': 'Student Skills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', through='student_profiles.StudentSkill', to='internships.skill'),
        ),
        migrations.AddConstraint(
            model_name='studentinterest',
            constraint=models.UniqueConstraint(fields=('student', 'interest'), name='unique_student_interest'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinterest',
            unique_together={('student', 'interest')},
        ),
        migrations.AddConstraint(
            model_name='studentskill',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill'),
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
    ]
