# Generated by Django 6.0.7 on 2026-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0014_careerinterest_studentinterest_student_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_year',
            field=models.CharField(blank=True, choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('final_year', 'Final Year'), ('graduate', 'Graduate'), ('other', 'Other')], help_text='Current academic year or status (fixed choice list).', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='Field of study code. The API validates against FIELD_OF_STUDY_CHOICES so the AI engine only sees canonical values.', max_length=150),
        ),
    ]
