# Generated by Django 6.0.7 on 2026-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0015_studentprofile_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='student_profiles.careerinterest'),
        ),
    ]
