# Generated by Django 6.0.7 on 2026-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0016_remove_studentprofile_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='available_from',
            new_name='availability_start',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='availability_start',
            field=models.DateField(blank=True, help_text='Earliest date the student is available for an internship.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='availability_end',
            field=models.DateField(blank=True, help_text='Latest date the student is available for an internship.', null=True),
        ),
    ]