# Generated by Django 6.0.7 on 2026-08-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0017_rename_studentprofile_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Canonical resume file. Uploaded via POST /api/students/me/resume/; referenced by the latest CV record for async parsing.', null=True, upload_to='student_resumes/'),
        ),
    ]
