# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0018_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume_parsed',
            field=models.BooleanField(default=False, help_text='True once the resume has been parsed by the async parse_resume Celery task.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_parsed_at',
            field=models.DateTimeField(blank=True, help_text='When the resume was last parsed by the async parse_resume task.', null=True),
        ),
    ]
