# Generated by Django 6.0.7 on 2026-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0019_studentprofile_resume_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('resume', 'Resume')], default='manual', help_text='Source of this skill: manually added by student or extracted from resume.', max_length=20),
        ),
    ]
