# Generated by Django 6.0.7 on 2026-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0020_studentskill_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_experience_years',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
