# Generated by Django 6.0.7 on 2026-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('api', 'Internship API'), ('rss', 'RSS feed'), ('career_website', 'Company career website'), ('job_portal', 'Job-portal API')], max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Data source',
                'verbose_name_plural': 'Data sources',
                'ordering': ['name'],
            },
        ),
    ]
