# Generated by Django 6.0.7 on 2026-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='website_url',
            new_name='base_url',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_type',
        ),
        migrations.AddField(
            model_name='datasource',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration dictionary for API keys, endpoints, and scraping parameters.'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('api', 'API'), ('rss', 'RSS Feed'), ('career_site', 'Career Site')], default='api', max_length=30),
        ),
    ]
